### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/animation/AnimatedContentScope;

### ISSUE THREAD

**Issue by GArustamyan** [fornewid/material-motion-compose#182]
## Describe the bug
"After updating the 'compose bom' to version '2023.03.00', the app crashes with the following exception:
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/animation/AnimatedContentScope;
                                                                                                    	at soup.compose.material.motion.MaterialMotionKt$MaterialMotion$3$1.invoke(MaterialMotion.kt:85)
                                                                                                    	at androidx.compose.animation.AnimatedContentKt.AnimatedContent(AnimatedContent.kt:759)
                                                                                                    	at soup.compose.material.motion.MaterialMotionKt.MaterialMotion(MaterialMotion.kt:83)
                                                                                                    	at soup.compose.material.motion.MaterialMotionKt.MaterialMotion(MaterialMotion.kt:55)
                                                                                                    	at soup.compose.material.motion.MaterialFadeThroughKt.MaterialFadeThrough(MaterialFadeThrough.kt:111)`

## To Reproduce
1. Update Compose Bom to 2023.03.00

## Environment
 - material-motion-compose version: 0.10.4

**Comment by fornewid** [comment]
[`0.11.1`](https://github.com/fornewid/material-motion-compose/releases/tag/v0.11.1) is released!
