### ISSUE TITLE
java.lang.NoSuchMethodError: No static method mutableStateOf(F)

### ISSUE THREAD

**Issue by GArustamyan** [fornewid/material-motion-compose#197]
**material motion compose = 1.0.2
compose version = 2023.05.01
compose compiler = 1.4.7**

java.lang.NoSuchMethodError: No static method mutableStateOf(F)Landroidx/compose/runtime/MutableFloatState; in class Landroidx/compose/runtime/PrimitiveSnapshotStateKt; or its super classes (declaration of 'androidx.compose.runtime.PrimitiveSnapshotStateKt'
                                                                                                    	at soup.compose.material.motion.MaterialMotionKt.MaterialMotion(MaterialMotion.kt:79)
                                                                                                    	at soup.compose.material.motion.MaterialMotionKt.MaterialMotion(MaterialMotion.kt:53)
                                                                                                    	at soup.compose.material.motion.MaterialFadeThroughKt.MaterialFadeThrough(MaterialFadeThrough.kt:40)

**Comment by fornewid** [comment]
The version compatible with Compose 1.4 is 0.11.3.
Could you please test with that version?

**Comment by feravolt** [comment]
Hi. I have same issue. 

`java.lang.NoSuchMethodError: No static method mutableStateOf(F)Landroidx/compose/runtime/MutableFloatState; in class Landroidx/compose/runtime/PrimitiveSnapshotStateKt; or its super classes (declaration of 'androidx.compose.runtime.PrimitiveSnapshotStateKt' appears in /data/app/~~Eyz8LSo9gz0itnGrzcC19w==/com.feravolt.fdeai-Mt5q80h8ZBoWZy8b6NKFog==/base.apk)
             	at soup.compose.material.motion.MaterialMotionKt.MaterialMotion(MaterialMotion.kt:79)
             	at soup.compose.material.motion.MaterialMotionKt.MaterialMotion(MaterialMotion.kt:53)`

Compose version = v1.5.0-beta02
Material Motion Compose = 1.0.2

**Comment by fornewid** [comment]
Can you reproduce it?
If so, please share the code.

**Comment by fornewid** [comment]
I think, this issue is related to https://issuetracker.google.com/issues/283828069.
And it was fixed on compose 1.5.0-beta02.
https://android-review.googlesource.com/c/platform/frameworks/support/+/2598825

So [material-motion-compose 1.0.3](https://github.com/fornewid/material-motion-compose/releases/tag/v1.0.3) is released.
Please check this issue on 1.0.3 version.
